platform: x64
configuration: Release
image: Visual Studio 2017

build:
  parallel: true                  # enable MSBuild parallel builds
  project: build\HM_vc10.sln      # path to Visual Studio solution or project