# For testing, we just create a test text file
script:
	- echo "Test text" > test.txt

after_success:
	- travis/push.sh
	
env:
  global:
    secure: GoxOW1Pc1V5K2Pk4QmDkWVPbpIV919YcZA3EW76eTM1+32ZUYvyIF60ji+7CJBXlLvvx318eHX8VBS0oYQbxleLEz6UCe/StCJLMUg0p+i3KvVkyIDANRQkk6W/9GUDNzCu9vboUPUdjkJ1BGxpTTxfv5et36etDLyD/BS6NSxsrn9kqxtjBRiUtQ0IBzFv7JByA8L89DGpSXS8A69GvprUDxftznWnGMQxXvKZ/Man1ZaL9mt4xhZFMOMLl7mtrdDL5Y95lWwxt/T3LFo4CNx0aGdGsXWByiyPyuL4iHetczcXsZE44ap9/z7h/SJibmLfDmtyp92duYhKBiydEZVsvs2QZiF6iuzgZen25/fSFhEJD5AA7xjvUFBTWPHwQqS203SJS6XNMIyZ4EJPOQsAYDR/ocHUSRCVMg8NbDEvJOqY+V2z7itGP2mxqEc2geD3l8L6RHVgFw5LzEClyHVNEEgsafY/eHhcXnVzEzQAW9P2YZyn3Lnz1iarBbfaXb0chmBQQgARnZT43ipuuwv8klgEFMGagTmrYIZjVZNn5Zmj/QCie+IcEju3UxhD7WUBHTHjUuizNUYp7fs6Vcc+SWC1enLW3QfHG8p+O2PRszaMr3EvUbyaFFuCzSdnMnFYGBRco+b/Gpb6k3moiqqjPW1djtjWYbFyN5BhEPV0=
	
	